title: "Natam Leão Ferreria"
author: "Natam L. Ferreria"
description: "My blog"
permalink: /:title/
lang: "pt-br"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:natamleaoferreira@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/natamleao"}
  - {title: Discord, icon: discord, url: "https://discord.com/users/natam_ferreira"}
  - {title: GitHub, icon: github, url: "https://github.com/natamleao"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
